### ISSUE TITLE
Seems there is an issue when dealing with ao 

### ISSUE THREAD

**Issue by lucus-lee** [Connum/npm-pinyin-separate#1]
Seems there is an issue when dealing with ao 
'piàoliàng'  is wrongl split into 'pià o liàng'

'cháo xiào' is wrongl split into 'cháo xià o'

**Comment by Connum** [comment]
Thanks for bringing this to my attention! I just made a push that should fix this.

**Comment by Connum** [comment]
BTW it's also available as a new [release ](https://github.com/Connum/npm-pinyin-separate/releases/tag/1.0.7)
